### PR TITLE
Send data to crm

### PR DESCRIPTION
**Pull request by autotelik**
Basic infrastructure for observers and jobs

Scaffold Contact

### CODE REVIEW

**Comment by lewispb** [comment]
Will this observer always trigger after every change to a contact? If so is that what we want, or do we want to just send everything at the end to reduce the number of API calls?

**Comment by autotelik** [comment]
@lewispb yep  the hook granularity is high level, like AR so after_save

But thats lightweight, and with that we can code whatever we like  .. so yes e.g we can only call the CRM job, once contact has all data we want present?

**Comment by lewispb** [comment]
I was thinking of sending over the application and all associated contacts / account info in one go at the end, but that may be several API calls anyway, so I guess it's just about figuring out what works for us. We can always change approach if needed anyways

**Comment by autotelik** [comment]
yeah it was more to just get the obersver/job pattern in place .. what we observe/send easy to change

**Pull request merged**
